import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WorkWave",
  description: "Generated by WorkWave team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>WorkWave</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Zain&display=swap" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
